### PR TITLE
fix motion completion condition, better implementation for activation

### PR DESCRIPTION
**Pull request by khoramshahi**
it is safer to update `activated` only at the callback.
I changed the movement completion condition also.
It complies and runs at our lab with Robotiq S model 2-fingers.

### CODE REVIEW

**Comment by AndyZe** [comment]
@MHornRobotics making sure you see this...

**Comment by MHornRobotics** [comment]
I believe we have a similar update for the Robotiq 3-Finger that waits to activate until it's commanded to activate. Will need to add a warning if we pull this, if activate isn't called when it's started, motion planners might not know the Robotiq's current position and cause collisions/crashes. Will merge pull request and add the warning then push it later this week, unless you have the time to Andy? We might also want to verify the movement completion condition works for our robotiq 2-finger as well.

**Review by Kukanani — COMMENTED** [review]
Thanks for the PR! I agree, the conditions checking probably needs some work.

Can you please clarify if you are using a 2-finger or 3-finger gripper? We may have the naming conventions wrong--in this package, "S-Model" refers to the 3-finger gripper, and "C-Model" to the 2-finger gripper. If you're using a 2-finger gripper, try `RCGripperInterface`.

If this is in fact for a 3-finger gripper (i.e. RSGripper), I'd ask @MHornRobotics or someone else at NRG (@cpetlowany?) to test this out on our own 3-finger gripper before merging.

**Comment by AndyZe** [comment]
I'm gonna merge because we have no easy way to test on a 2-finger gripper. Thank you!

**Comment by Kukanani** [comment]
FYI @cpetlowany , we should probably hold off on pulling this change until we know if it affects our use of the 3-finger gripper.

**Pull request merged**
